<?php
/**
 * Created by PhpStorm.
 * Users: nengliu
 * Date: 2017/8/29
 * Time: 下午4:20
 */
namespace backend\models;

use yii;
use yii\rbac\Item;

class PermissionForm extends AuthItem
{
    /**
     * 初始化权限类型.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->type = Item::TYPE_PERMISSION;
    }

}