<?php
/**
 * Created by PhpStorm.
 * User: nengliu
 * Date: 2017/8/29
 * Time: 下午4:20
 */

namespace backend\models;

use yii;
use yii\rbac\Item;

class RoleForm extends AuthItem
{

    /**
     * 初始化角色类型.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->type = Item::TYPE_ROLE;
    }

}